### ISSUE TITLE
Added used languages tags

### ISSUE THREAD

**Issue by avelino** [jbochi/hackaton_rank#4]
API samples: https://api.github.com/repos/{owner}/{repo}/languages

**Comment by jbochi** [comment]
Awesome idea. @tarsisazevedo, #fikaadika #freela

**Comment by tarsisazevedo** [comment]
doing.

**Comment by jbochi** [comment]
Fixed by 4e47a4bd1d80f392e7c0f7f6c099b4a4b3c0864d.

Thanks, @tarsisazevedo !!!
